name: shop_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - font/assets/shoes_1.png
    - font/assets/shoes_2.png
    - font/assets/shoes_3.png
    - font/assets/shoes_4.png
  fonts:
    - family: Lato
      fonts:
        - asset: font/Lato-Bold.ttf
        - asset: font/Lato-Light.ttf
          weight: 700
    - family: xxx
      fonts:
        - asset: font/BBHBartle-Regular.ttf
          weight: 400      

